<?php

declare(strict_types=1);

namespace App\Services;

use App\Contracts\Services\ProjectActivityServiceInterface;
use App\Models\ActivityLog;
use App\Models\Project;
use App\Repositories\Contracts\ActivityLogRepositoryInterface;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 * Read facade for Activity Studio. Does not invent records — it only lists
 * existing activity_logs rows generated by real studio actions.
 */
final readonly class ProjectActivityService implements ProjectActivityServiceInterface
{
    public function __construct(
        private ActivityLogRepositoryInterface $activityLogs,
    ) {}

    public function paginateForProject(Project $project, int $perPage = 15, array $filters = []): LengthAwarePaginator
    {
        return $this->activityLogs->paginateForProject($project, $perPage, $filters);
    }
}
